
services:

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    image: mariadb
    volumes:
      - database:/var/lib/mysql
    env_file:
      - .env
    networks:
      - my-network
    restart: always

  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my-network
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress-data:/var/www/html
    env_file:
      - .env
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: bridge
volumes:
  wordpress-data:
    driver_opts:
      o: bind
      type: none
      device: /home/imaaitat/data/wp
  database:
    driver_opts:
      o: bind
      type: none
      device: /home/imaaitat/data/db

